version: '3.8'

services:
  avito-shop-service-test:
    build: ..
    container_name: avito-shop-service-test
    ports:
      - "8081:8080"
    environment:
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=shop
      - DATABASE_HOST=db-test
      - SERVER_PORT=8080
      - JWT_SECRET=f1a8642fe7cd
    depends_on:
      db-test:
        condition: service_healthy
    networks:
      - internal

  db-test:
    image: postgres:13
    container_name: postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d shop'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal
networks:
  internal: